### PR TITLE
Zp02/feat/portfolio landing page filled state

### PR DESCRIPTION
**Pull request by fabrizia2**
you can check this one that was used for the previous cohort

# Fixes Issue/Linear Ticket

> This could be an existing issue or a linear ticket
>
> - Github Issue Example: My PR Closes #{ISSUE}
> - Linear Ticket Example: Fixes ID-#{ISSUE}

# Changes proposed

> Talk about the things you did eg. files changes, dependencies installed e.t.c

# Check List (Check all the applicable boxes)

:rotating_light:Please review the [style guide for contributing](add link here) and [guidelines for contributing](add link here) to this repository.

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR is clear and explains the approach.
- [x] I am making a pull request against the **main branch** (left side).
- [x] My commit messages styles matches our requested structure.
- [x] My code additions will fail neither code linting checks nor unit test.
- [x] I am only making changes to files I was requested to.

# Screenshots/ Videos

### CODE REVIEW

**Comment by fabrizia2** [comment]
prof

**Comment by fabrizia2** [comment]
prof

**Comment by fabrizia2** [comment]
[https://www.loom.com/share/1c05fcd808c64a28bc672776ad48a0ba?sid=211c0674-3499-4586-8071-5173954ba75d](url)

**Review by shalomtaiwo — CHANGES_REQUESTED** [review]
fix yarn.lock

**Comment by fabrizia2** [comment]
Fixed @shalomtaiwo

**Comment by fabrizia2** [comment]
https://github.com/hngx-org/zuriportfolio-frontend/assets/107267216/0ae36050-b448-46ab-baac-389502448c3d

**Pull request closed without merging**
