### PR TITLE
Zc001/feat/cart page design

### LINKED ISSUE #10: Feat Cart-Page-Design
Design a responsive page to view products in cart

### PR DESCRIPTION
**Pull request by Homoakin619**
you can check this one that was used for the previous cohort
# Fixes Issue/Linear Ticket
> This could be an existing issue or a linear ticket
> - Github Issue Example: My PR Closes #10 
> - Linear Ticket Example: Fixes ID-#{ISSUE}
# Changes proposed
> I implemented the design for the cart page and added responsiveness
# Check List (Check all the applicable boxes)
:rotating_light:Please review the [style guide for contributing](add link here) and [guidelines for contributing](add link here) to this repository.
- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR is clear and explains the approach.
- [x] I am making a pull request against the **main branch** (left side).
- [x] My commit messages styles matches our requested structure.
- [x] My code additions will fail neither code linting checks nor unit test.
- [x] I am only making changes to files I was requested to.
# Screenshots/ Videos

### CODE REVIEW

**Review by shalomtaiwo — CHANGES_REQUESTED** [review]
Please answer on Slack why the Tailwind config was modified. This should not be modified unless requested first

**Comment by Homoakin619** [comment]
The changes to the tailwind config has been removed

**Review by shalomtaiwo — CHANGES_REQUESTED** [review]
Please pull from dev branch and update local files. After that I'll push the PR

**Comment by Homoakin619** [comment]
Local files have been updated, you can merge now

**Review by shalomtaiwo — APPROVED** [review]

**Pull request merged**
