### PR TITLE
ZA-009/feat/verification-complete

### PR DESCRIPTION
**Pull request by oluwaseunolafisoye**
# Fixes Issue/Linear Ticket
> - Linear Ticket: Fixes ID-#ZA-009

# Changes proposed
> - Created the **Verification Complete** page and took attention to responsiveness and following the design as close as possible. 

# Check List (Check all the applicable boxes)

:rotating_light:Please review the [style guide for contributing](add link here) and [guidelines for contributing](add link here) to this repository.

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR is clear and explains the approach.
- [x] I am making a pull request against the **main branch** (left side).
- [x] My commit messages styles matches our requested structure.
- [x] My code additions will fail neither code linting checks nor unit test.
- [x] I am only making changes to files I was requested to.

Screenshot (43)
Screenshot (42)
Screenshot (41)

### CODE REVIEW

**Review by shalomtaiwo — COMMENTED** [review]
Verification for? There's already an existing verification page.  Is this an addition or a new one

**Comment by oluwaseunolafisoye** [comment]
it’s a confirmation page that the verification has been sent. That’s the third page assigned to me.

**Review by shalomtaiwo — CHANGES_REQUESTED** [review]
Change your routes. There's already an existing verification route

**Comment by oluwaseunolafisoye** [comment]
I have done that and even linked the pages. but there're errors regarding apostrophe in the codebase that's not allowing me to commit and push.

**Review by shalomtaiwo — APPROVED** [review]

**Pull request merged**
