### PR TITLE
fix: mobile reponsiveness

### PR DESCRIPTION
**Pull request by Goodness5**
added responsiveness for mobile screens
Screenshot from 2023-10-07 10-28-21
Screenshot from 2023-10-07 10-28-35
Screenshot from 2023-10-07 10-28-42
Screenshot from 2023-10-07 10-29-03

### CODE REVIEW

**Review by shalomtaiwo — CHANGES_REQUESTED** [review]
resolve the conflicts

**Comment by Goodness5** [comment]
conflicts resolved @shalomtaiwo

**Review by phoenixdahdev — CHANGES_REQUESTED** [review]
rsolve the conflict maam

**Review by phoenixdahdev — APPROVED** [review]
passed

**Review by shalomtaiwo — APPROVED** [review]

**Pull request merged**
