### PR TITLE
Sup2 2/feat/feedback and customer support

### PR DESCRIPTION
**Pull request by Philipudofia**
created customer complaint page for vendor
below is the screenshot of the view
{04FDB6CC-59D6-46E3-ACE4-8F50E86A0F25} png

### CODE REVIEW

**Review by shalomtaiwo — CHANGES_REQUESTED** [review]
Screenshot

**Comment by Philipudofia** [comment]
hello shalom, please what exactly am i to screenshot shot

**Comment by Philipudofia** [comment]
This is a screenshot of the complaints page
{04FDB6CC-59D6-46E3-ACE4-8F50E86A0F25} png

**Review by shalomtaiwo — APPROVED** [review]

**Comment by shalomtaiwo** [comment]
Reverts

**Pull request merged**
